using Dziennik.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;

namespace Dziennik.DAL
{
    public abstract class Database
    {
        public abstract ICollection<Klasa> GetKlasyAll();
        public abstract ICollection<Konto> GetKontaAll();
        public abstract ICollection<Lekcja> GetLekcjeAll();
        public abstract ICollection<Lekcja> GetLekcjeDate();
        public abstract ICollection<Nauczanie> GetNauczaniaAll();
        public abstract ICollection<Konto> GetNauczycielAll();
        public abstract ICollection<Obecnosc> GetObecnosciAll();
        public abstract ICollection<Ocena> GetOcenyAll();
        public abstract ICollection<Przedmiot> GetPrzedmiotyAll();
        public abstract ICollection<Konto> GetUczniowieAll();
        public abstract ICollection<Wydarzenie> GetWydarzeniaAll();
        public abstract ICollection<Semestr> GetSemestryAll();
        public abstract ICollection<Nauczanie> GetNauczaniaNauczyciel(int id);
        public abstract ICollection<Konto> GetUczniowieKlasa(int id);
        public abstract ICollection<Obecnosc> GetObecnosciLekcja(int id);
        public abstract ICollection<Lekcja> GetLekcjeKlasa(int id);
        public abstract Semestr GetSemestr(int id);
        public abstract ICollection<Obecnosc> GetObecnosciUczen(int id);
        public abstract ICollection<Konto> GetUczniowieWychowawca(int id);
        public abstract ICollection<Wiadomosc> GetWiadomosciKonta(int id);
        public abstract ICollection<Lekcja> GetLekcjeNauczanie(int id);
        public abstract ICollection<Ocena> GetOcenyUczen(int id);
        public abstract ICollection<Ocena> GetOcenyPrzedmiot(int id);
        public abstract ICollection<Wydarzenie> GetWydarzeniaUczen(int id);
        public abstract ICollection<Wydarzenie> GetWydarzeniaNauczyciel(int id);
        public abstract Konto GetUczen(int id);
        public abstract Konto GetUczenKonto(int id);
        public abstract Konto GetNauczyciel(int id);
        public abstract Konto GetNauczycielKonto(int id);
        public abstract Przedmiot GetPrzedmiot(int id);
        public abstract Konto GetKontoLogin(string login);
        public abstract Ocena GetOcena(int id);
        public abstract Klasa GetKlasa(int id);
        public abstract Wiadomosc GetWiadomosc(int id);
        public abstract Wydarzenie GetWydarzenie(int id);
        public abstract Lekcja GetLekcja(int id);
        public abstract Obecnosc GetObecnosc(int id);
        public abstract Klasa GetKlasaWychowawca(int id);
        public abstract Konto GetKontoUczen(int id);
        public abstract Konto GetUczenLogin(string login);
        public abstract string GetHasloLogin(string login);
        public abstract void CreateKonto(Konto konto);
        public abstract void CreateUczen(Konto uczen);
        public abstract void CreateNauczyciel(Konto nauczyciel);
        public abstract void CreateOcena(Ocena ocena);
        public abstract void CreateWydarzenie(Wydarzenie wydarzenie);
        public abstract void CreatePrzedmiot(Przedmiot przedmiot);
        public abstract void CreateSemestr(Semestr semestr);
        public abstract void CreateKlasa(Klasa klasa);
        public abstract void CreateObecnosc(Obecnosc obecnosc);
        public abstract void CreateLekcja(Lekcja lekcja);
        public abstract void CreateWiadomosc(Wiadomosc wiadomosc);
        public abstract void UpdateOcena(Ocena ocena);
        public abstract void UpdateWydarzenie(Wydarzenie wydarzenie);
        public abstract void UpdateObecnosc(Obecnosc obecnosc);
        public abstract void UpdatePassword(string login, string password);
        public abstract void UpdateEmail(string login, string email);
        public abstract void UpdateStudent(Konto uczen);
        public abstract void UpdateClass(Klasa klasa);
        public abstract void UpdateSemestr(Semestr semestr);
        public abstract void UpdatePrzedmiot(Przedmiot przedmiot);
        public abstract void UpdateStudentClass(int user_id, int class_id);
        public abstract void DeleteOcena(int id);
        public abstract void DeleteWydarzenie(int id);
        public abstract void DeleteObecnosc(int id);
        public abstract void DeleteWiadomosc(int id);
        public abstract void DeleteUczen(int id);
        public abstract void DeletePrzedmiot(int id);
        public abstract void BlockStudent(int id);
        public abstract void UnblockStudent(int id);
    }
}
